### ISSUE TITLE
WorkModeParameter no longer working

### ISSUE THREAD

**Issue by pjenningsuk1** [dmarjoram/Roses.SolarAPI#6]
Hi, not sure if I broke it when I updated the Docker install to the latest version, but the 3 WorkMode options are not working and in the swagger now return:
{
  "resultCode": "InvalidRequest"
}
![WMP](https://user-images.githubusercontent.com/98637499/199969880-26a5ddce-3e08-4244-a66f-ebc6cc25d692.png)

The logs in docker are attached

The only other complication with my setup is that I have 2 inverters under the 1 fox cloud account, but this wasn't an issue before...

**Comment by pjenningsuk1** [comment]
Could it be the 
"key`":`"h109__02__00`",`"values`":{`"h109__02__00`" 
have changed from 
"key`":`"h106__02__00`",`"values`":{`"h106__02__00`"
??

**Comment by davidvalasek** [comment]
Are you going to fix it, please?

+1

**Comment by pjenningsuk1** [comment]
Hi, I ended up copying [dmarjoram] project and modifying it myself and using my own version. I am not sure where Darrell is, perhaps he has run out of time?

If you want to download mine from docker, it is here and works in the same way as this project, just with the modified keys

https://hub.docker.com/r/pjenningsuk/foxapi

**Comment by Fred749** [comment]
> Hi, I ended up copying [dmarjoram] project and modifying it myself and using my own version. I am not sure where Darrell is, perhaps he has run out of time?
> 
> If you want to download mine from docker, it is here and works in the same way as this project, just with the modified keys
> 
> https://hub.docker.com/r/pjenningsuk/foxapi

Hi pjenningsuk1,

I tried download your version, but I got error:
docker pull pjenningsuk/foxapi
Using default tag: latest
Error response from daemon: manifest for pjenningsuk/foxapi:latest not found: manifest unknown: manifest unknown

**Comment by pjenningsuk1** [comment]
Try this:
docker pull pjenningsuk/foxapi:april2023

**Comment by Fred749** [comment]
> Try this:
> docker pull pjenningsuk/foxapi:april2023

Thanks, pjenningsuk1. I downloaded and run, but I have still same error :-(
<img width="811" alt="Fox_api" src="https://github.com/dmarjoram/Roses.SolarAPI/assets/112810004/585ec7f6-52b7-446f-96d9-69295e3df227">
Any idea please?

**Comment by pjenningsuk1** [comment]
Can you confirm you have this option now on the FoxESS cloud website?
![image](https://github.com/dmarjoram/Roses.SolarAPI/assets/98637499/d35c7326-c3ca-4573-b64e-2238be55657b)


If so, I will change the docker build to use that instead
![image](https://github.com/dmarjoram/Roses.SolarAPI/assets/98637499/a0c29ccc-cdec-4a77-92c7-7b7931452d97)

**Comment by pjenningsuk1** [comment]
Or if you can turn on Dev mode and confirm the key as per below (shown in Chrome) when slecting the work mode at https://www.foxesscloud.com/bus/device/inverter/remoteSetting?


![image](https://github.com/dmarjoram/Roses.SolarAPI/assets/98637499/f0c0a0da-3c17-44bb-b50c-3816d6c58182)

**Comment by davidvalasek** [comment]
Hello, it asks for password every time changing workmode + key is

![Snímek obrazovky 2023-05-23 v 18 51 24](https://github.com/dmarjoram/Roses.SolarAPI/assets/112775156/d2ca84b5-ead5-44a3-b080-021930006c8f)

**Comment by Fred749** [comment]
> Can you confirm you have this option now on the FoxESS cloud website? ![image](https://user-images.githubusercontent.com/98637499/240358175-d35c7326-c3ca-4573-b64e-2238be55657b.png)
> 
> If so, I will change the docker build to use that instead ![image](https://user-images.githubusercontent.com/98637499/240358323-a0c29ccc-cdec-4a77-92c7-7b7931452d97.png)

Yes, I have this option on the FoxESS cloud website.

**Comment by Fred749** [comment]
> Or if you can turn on Dev mode and confirm the key as per below (shown in Chrome) when slecting the work mode at https://www.foxesscloud.com/bus/device/inverter/remoteSetting?
> 
> ![image](https://user-images.githubusercontent.com/98637499/240359320-f0c0a0da-3c17-44bb-b50c-3816d6c58182.png)

Here is a screen from dev mode in Chrome.
<img width="1252" alt="Dev" src="https://github.com/dmarjoram/Roses.SolarAPI/assets/112810004/d7f8a3d8-3d18-416c-96f9-50a9d2963ec9">

**Comment by pjenningsuk1** [comment]
ok, I see your key is d108. Let me look into that. Are you on the latest version of firmware or older version? Did this docker ever work for you, or are you only just trying it?

**Comment by Fred749** [comment]
I have a  inverter AIO-H3-10.0. Firmware are:
Master: 1.33 (latest)
Slave: 1.0 (there is no option to choose fw upgrade)
Manager: 1.37 (latest)

This docker was work for me for settings battery SoC and charge from grid. I've never tried change workmode from this docker. For example setting battery SoC not working too.
I tried now and fox_force_charge_now + fox_force_charge_stop still working.

**Comment by Fred749** [comment]
Hi @pjenningsuk1, any news, please?

**Comment by pjenningsuk1** [comment]
Funnily enough, I have had some time this morning.

Try:
docker pull pjenningsuk/foxapi:d108

**Comment by Fred749** [comment]
@pjenningsuk1 Thanks a lot, but still not working. Here is a screen from the log.
I see in log "Using modbus TCP to IP address 192.168.0.153 on port 502. Device ID is set to 247", but that is not my IP of the modbus. 
<img width="797" alt="Log" src="https://github.com/dmarjoram/Roses.SolarAPI/assets/112810004/6722562e-4589-4ebd-bf7c-61b1123bb4f4">

**Comment by pjenningsuk1** [comment]
Ignore the modbus for the minute, we are focused on sending the command to the foxess cloud to change the work mode. Let me scratch my head again. I can see it is trying d108 in there, but it is not liking it.

**Comment by pjenningsuk1** [comment]
Can you confirm the set command in dev mode:
![image](https://github.com/dmarjoram/Roses.SolarAPI/assets/98637499/5cc7d0cd-89a1-4455-bfc7-51bd7f9d547f)

**Comment by Fred749** [comment]
About modbus I understand, but that would be great set Workmode and other parametrs via modbus instead of FoxCloud :-) 
Here is a screen:
<img width="993" alt="Set" src="https://github.com/dmarjoram/Roses.SolarAPI/assets/112810004/c0e22502-9227-4957-95ee-4cd4626b3a4f">

**Comment by pjenningsuk1** [comment]
Try this if you like:
docker pull pjenningsuk/foxapi:d108b

When first run the image, it gives you options as follows:
![image](https://github.com/dmarjoram/Roses.SolarAPI/assets/98637499/b5cc9120-b2e9-44d6-8855-e6f1ad297663)


FOXESSCONFIGURATION__IPADDRESS
FOXESSCONFIGURATION__USERNAME
FOXESSCONFIGURATION__PASSWORDMD5HASH 
FOXESSCONFIGURATION__SERIALNUMBER 
FOXESSCONFIGURATION__CLOUDDEVICEID
TZ | Europe/London |

**Comment by pjenningsuk1** [comment]
The above info was to confirm where you specify the IPADDRESS of the modbus.
I.e. you need to add to the environment variables

**Comment by Fred749** [comment]
you are a genius :) The settings via FoxCloud working now!! I tested set work modes, battery SoC and works it. 
Via modbus not working for me, I tried set minSoC (/FoxESS/Local/SetBatteryMonSoC) and page is still loading, but you helped me a lot, that I can set Workmodes ;-)
<img width="769" alt="latest" src="https://github.com/dmarjoram/Roses.SolarAPI/assets/112810004/b43b32c5-92b3-4758-ad62-5ecccf51d4dd">

**Comment by davidvalasek** [comment]
thx guys to get it working, great job! ;)

**Comment by davidvalasek** [comment]
is there possible to set export limit too?

**Comment by pjenningsuk1** [comment]
OK, I am please. I will keep the project for the all-in-one inverter as well as the one I have for my H series inverter. So that if it changes again in the future, I can tweak and repost.

**Comment by pjenningsuk1** [comment]
> is there possible to set export limit too?

What is it you want to achieve? I use Home Assistant to monitor the export prices and kWh production etc to change the work mode to export or battery self charge.

Changing export limit disregards the energy over that value and no one benefits.

**Comment by davidvalasek** [comment]
We have on holidays, sundays, german holidays, etc. negative spot prices often during day, so we pay extra fee if we export these days to grid. These days we have to set export limit to 0.

**Comment by pjenningsuk1** [comment]
Ah, now I understand. I will keep it in mind and see if we can include going forward

**Comment by davidvalasek** [comment]
Thank you in advance. If we can support you “buy you a coffee” or smth, let me know.

**Comment by davidvalasek** [comment]
@pjenningsuk1  Hello, could you please try to add export limit function? During summer it should help us to use automations like today. 
![image](https://github.com/dmarjoram/Roses.SolarAPI/assets/112775156/1d5b665f-08ab-4871-82d1-cc97fb0ab352)

**Comment by davidvalasek** [comment]
@pjenningsuk1 pls

**Comment by dmarjoram** [comment]
Now fixed in V1.5. You can pull latest images from Docker hub.

**Comment by dmarjoram** [comment]
Work mode can now also be set via modbus (local) in v1.51

**Comment by dmarjoram** [comment]
> About modbus I understand, but that would be great set Workmode and other parametrs via modbus instead of FoxCloud :-) Here is a screen: <img alt="Set" width="993" src="https://user-images.githubusercontent.com/112810004/241750877-c0e22502-9227-4957-95ee-4cd4626b3a4f.png">

Now available in docker tag V1.51

**Comment by Fred749** [comment]
@dmarjoram Hi, many thanks, I tested it via modbus and works it. Could you please try to add export limit function yet? During summer it should help us to use automations like today as David wrote.
