### ISSUE TITLE
Source for FoxESSRegisters?

### ISSUE THREAD

**Issue by w0ut0** [dmarjoram/Roses.SolarAPI#7]
Hello!
What is the source for the local modbus registers (eg. to control battery min soc etc.)?

If there is a confirmed source, I'm hopeful we can integrate this in the native [FoxESS Modbus Home Assistant integration](https://github.com/StealthChesnut/HA-FoxESS-Modbus). 
There is an [open issue](https://github.com/StealthChesnut/HA-FoxESS-Modbus/issues/28) for confirmed battery settings registers.

**Comment by dmarjoram** [comment]
Trial and error
